# Generated by Django 5.0.1 on 2024-01-09 17:30

import ProductApp.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=ProductApp.models.filePath)),
            ],
        ),
    ]
